if(!require(shiny)){
  install.packages("shiny")
}
if(!require(shinyBS)){
  install.packages(shinyBS)
}
if(!require(tidyverse)){
  install.packages(tidyverse)
}
if(!require(tidytext)){
  install.packages(tidytext)
}
if(!require(plotly)){
  install.packages(plotly)
}
if(!require(knitr)){
  install.packages(knitr)
}
if(!require(vroom)){
  install.packages(vroom)
}
if(!require(tippy)){
  install.packages(tippy)
}

library(shiny)
library(shinyBS)
library(tidyverse)
library(tidytext)
library(plotly)
library(knitr)
library(vroom)
library(tippy)